import Head from 'next/head'
import classes from '../styles/Home.module.css'
import { Footer } from '../components/Footer/Footer'
import { Main } from '../components/Main/Main'

export default function about() {
  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main page={"about"}/>

      <Footer />
    </div>
  )
}
