import Head from 'next/head'
import classes from '../styles/Home.module.css'
import { Footer } from '../../components/Footer/Footer'
import { Main } from '../../components/Main/Main'
import { Header } from '../components/Header/Header'


export default function Home() {
  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Main page={"index"}/>

      <Footer />
    </div>
  )
}
